# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scan.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='scan.proto',
  package='main',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\nscan.proto\x12\x04main\x1a\x1fgoogle/protobuf/timestamp.proto\"\'\n\tReference\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\"\x8a\x02\n\rVulnerability\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x0f\n\x07summary\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x39\n\x0bidentifiers\x18\x05 \x03(\x0b\x32$.main.Vulnerability.IdentifiersEntry\x12 \n\x08severity\x18\x06 \x01(\x0e\x32\x0e.main.Severity\x12#\n\nreferences\x18\x07 \x03(\x0b\x32\x0f.main.Reference\x1a\x32\n\x10IdentifiersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"K\n\x0bLayerResult\x12\x0e\n\x06sha256\x18\x01 \x01(\t\x12,\n\x0fvulnerabilities\x18\x02 \x03(\x0b\x32\x13.main.Vulnerability\"\x8d\x01\n\x04Scan\x12\x1e\n\x07\x62\x61\x63kend\x18\x01 \x01(\x0e\x32\r.main.Scanner\x12\x0e\n\x06target\x18\x02 \x01(\t\x12+\n\x07\x63reated\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12(\n\rlayer_results\x18\x04 \x03(\x0b\x32\x11.main.LayerResult*Q\n\x08Severity\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07TRIVIAL\x10\x01\x12\x07\n\x03LOW\x10\x02\x12\n\n\x06MEDIUM\x10\x03\x12\x08\n\x04HIGH\x10\x04\x12\x0c\n\x08\x43RITICAL\x10\x05**\n\x07Scanner\x12\n\n\x06\x44OCKER\x10\x00\x12\x08\n\x04SNYK\x10\x01\x12\t\n\x05TRIVY\x10\x02\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])

_SEVERITY = _descriptor.EnumDescriptor(
  name='Severity',
  full_name='main.Severity',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRIVIAL', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOW', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MEDIUM', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HIGH', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CRITICAL', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=584,
  serialized_end=665,
)
_sym_db.RegisterEnumDescriptor(_SEVERITY)

Severity = enum_type_wrapper.EnumTypeWrapper(_SEVERITY)
_SCANNER = _descriptor.EnumDescriptor(
  name='Scanner',
  full_name='main.Scanner',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DOCKER', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SNYK', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRIVY', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=667,
  serialized_end=709,
)
_sym_db.RegisterEnumDescriptor(_SCANNER)

Scanner = enum_type_wrapper.EnumTypeWrapper(_SCANNER)
UNKNOWN = 0
TRIVIAL = 1
LOW = 2
MEDIUM = 3
HIGH = 4
CRITICAL = 5
DOCKER = 0
SNYK = 1
TRIVY = 2



_REFERENCE = _descriptor.Descriptor(
  name='Reference',
  full_name='main.Reference',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='main.Reference.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='url', full_name='main.Reference.url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=92,
)


_VULNERABILITY_IDENTIFIERSENTRY = _descriptor.Descriptor(
  name='IdentifiersEntry',
  full_name='main.Vulnerability.IdentifiersEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='main.Vulnerability.IdentifiersEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='main.Vulnerability.IdentifiersEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=311,
  serialized_end=361,
)

_VULNERABILITY = _descriptor.Descriptor(
  name='Vulnerability',
  full_name='main.Vulnerability',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='main.Vulnerability.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='main.Vulnerability.version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='summary', full_name='main.Vulnerability.summary', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='main.Vulnerability.description', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='identifiers', full_name='main.Vulnerability.identifiers', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='severity', full_name='main.Vulnerability.severity', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='references', full_name='main.Vulnerability.references', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_VULNERABILITY_IDENTIFIERSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=361,
)


_LAYERRESULT = _descriptor.Descriptor(
  name='LayerResult',
  full_name='main.LayerResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sha256', full_name='main.LayerResult.sha256', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vulnerabilities', full_name='main.LayerResult.vulnerabilities', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=363,
  serialized_end=438,
)


_SCAN = _descriptor.Descriptor(
  name='Scan',
  full_name='main.Scan',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='backend', full_name='main.Scan.backend', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target', full_name='main.Scan.target', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created', full_name='main.Scan.created', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='layer_results', full_name='main.Scan.layer_results', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=441,
  serialized_end=582,
)

_VULNERABILITY_IDENTIFIERSENTRY.containing_type = _VULNERABILITY
_VULNERABILITY.fields_by_name['identifiers'].message_type = _VULNERABILITY_IDENTIFIERSENTRY
_VULNERABILITY.fields_by_name['severity'].enum_type = _SEVERITY
_VULNERABILITY.fields_by_name['references'].message_type = _REFERENCE
_LAYERRESULT.fields_by_name['vulnerabilities'].message_type = _VULNERABILITY
_SCAN.fields_by_name['backend'].enum_type = _SCANNER
_SCAN.fields_by_name['created'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_SCAN.fields_by_name['layer_results'].message_type = _LAYERRESULT
DESCRIPTOR.message_types_by_name['Reference'] = _REFERENCE
DESCRIPTOR.message_types_by_name['Vulnerability'] = _VULNERABILITY
DESCRIPTOR.message_types_by_name['LayerResult'] = _LAYERRESULT
DESCRIPTOR.message_types_by_name['Scan'] = _SCAN
DESCRIPTOR.enum_types_by_name['Severity'] = _SEVERITY
DESCRIPTOR.enum_types_by_name['Scanner'] = _SCANNER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Reference = _reflection.GeneratedProtocolMessageType('Reference', (_message.Message,), {
  'DESCRIPTOR' : _REFERENCE,
  '__module__' : 'scan_pb2'
  # @@protoc_insertion_point(class_scope:main.Reference)
  })
_sym_db.RegisterMessage(Reference)

Vulnerability = _reflection.GeneratedProtocolMessageType('Vulnerability', (_message.Message,), {

  'IdentifiersEntry' : _reflection.GeneratedProtocolMessageType('IdentifiersEntry', (_message.Message,), {
    'DESCRIPTOR' : _VULNERABILITY_IDENTIFIERSENTRY,
    '__module__' : 'scan_pb2'
    # @@protoc_insertion_point(class_scope:main.Vulnerability.IdentifiersEntry)
    })
  ,
  'DESCRIPTOR' : _VULNERABILITY,
  '__module__' : 'scan_pb2'
  # @@protoc_insertion_point(class_scope:main.Vulnerability)
  })
_sym_db.RegisterMessage(Vulnerability)
_sym_db.RegisterMessage(Vulnerability.IdentifiersEntry)

LayerResult = _reflection.GeneratedProtocolMessageType('LayerResult', (_message.Message,), {
  'DESCRIPTOR' : _LAYERRESULT,
  '__module__' : 'scan_pb2'
  # @@protoc_insertion_point(class_scope:main.LayerResult)
  })
_sym_db.RegisterMessage(LayerResult)

Scan = _reflection.GeneratedProtocolMessageType('Scan', (_message.Message,), {
  'DESCRIPTOR' : _SCAN,
  '__module__' : 'scan_pb2'
  # @@protoc_insertion_point(class_scope:main.Scan)
  })
_sym_db.RegisterMessage(Scan)


_VULNERABILITY_IDENTIFIERSENTRY._options = None
# @@protoc_insertion_point(module_scope)
